services:
  - type: web
    name: undefine
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PROVIDER
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/word
    autoDeploy: true 