services:
  - type: web
    name: undefine-backend
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PROVIDER
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /api/word
    autoDeploy: true 