-- Create the WORDS table
CREATE TABLE IF NOT EXISTS WORDS (
    ID VARCHAR(36) DEFAULT UUID_STRING(),
    WORD VARCHAR(255) NOT NULL,
    DEFINITION TEXT NOT NULL,
    PART_OF_SPEECH VARCHAR(50) NOT NULL,
    TIMES_USED NUMBER DEFAULT 0,
    LAST_USED_DATE TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

-- Create a clustering key on the WORD column
ALTER TABLE IF EXISTS WORDS CLUSTER BY (WORD);

-- Enable search optimization
ALTER TABLE IF EXISTS WORDS ADD SEARCH OPTIMIZATION;

-- Create a stream for tracking changes
CREATE STREAM IF NOT EXISTS WORDS_STREAM ON TABLE WORDS;

-- Create a task to update the UPDATED_AT timestamp
CREATE OR REPLACE TASK UPDATE_WORDS_TIMESTAMP
    WAREHOUSE = UNDEFINE
    SCHEDULE = '1 minute'
AS
    UPDATE WORDS
    SET UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE ID IN (
        SELECT ID 
        FROM WORDS_STREAM
        WHERE METADATA$ACTION = 'INSERT' OR METADATA$ACTION = 'UPDATE'
    );

-- Start the task
ALTER TASK UPDATE_WORDS_TIMESTAMP RESUME; 